---
services:
  fogserver:
    # image: linkat/fogproject:1.0.3
    build: .
    container_name: fogproject
    hostname: fogproject
    restart: always
    environment:
      TZ: Europe/Paris
      IP: 192.168.1.225
      WEBSERVER_HTTP_PORT: 80
      APACHE_ROOT_REDIRECTION: "/fog"
    ports:
      - 80:80/tcp
      - 69:69/tcp
      - 69:69/udp
      - 21:21/tcp
#      - 443:443/tcp
      - 9000:9000/tcp
    volumes:
      - ./fogproject_images:/images
      - ./fogproject_mysql_data:/var/lib/mysql
